---

- hosts: localhost
  connection: local
  become: false
  vars:
    group_role: cluster-admin
    GITHUB_ORGANIZATION: open-cluster-management
    GITHUB_TOKEN: "{{ lookup('env', 'GITHUB_TOKEN') | default('', True) }}"
    home: "{{ lookup('env', 'HOME') | default('', True) }}"
    organization_groups:
    - SRE
    optional_vars_file: "{{ home }}/external_vars.yml"
  tasks:

  - include_vars: "{{ optional_vars_file }}"
    when: optional_vars_file is file

  - name: Patch the clusterdeployment with label purpose=pm-demo
    shell: |
      oc get cd -l purpose=pm-demo -A --no-headers | awk '{print $1}' | xargs -I % oc patch clusterdeployment/% -n % --type=json --patch='[ { "op": "add", "path": "/spec/preserveOnDelete", "value":true}]'
    register: output

  - name: oc patch clusterdeployment -l purpose=pm-demo
    debug:
      msg: 
      - "{{ output.stdout_lines }}"
