---

- hosts: localhost
  connection: local
  become: false
  vars:
    RHACM_PULL_SECRET_YAML_FILE: "~/rhacm-pull-secret.yaml"
    IDP_MGMT_VERSION: "{{ lookup('env', 'IDP_MGMT_VERSION') | default('v0.1.0', True) }}"
    home: "{{ lookup('env', 'HOME') | default('', True) }}"
    optional_vars_file: "{{ home }}/external_vars.yml"
    kubeconfig_file: "{{ lookup('env', 'KUBECONFIG') | default('', True) }}"
    kubectl_cmd: "oc --insecure-skip-tls-verify=true"
  tasks:

  - include_vars: "{{ optional_vars_file }}"
    when: optional_vars_file is file

  - name: Deploy idp-mgmt operator
    block:
    - name: Generate idp-mgmt manifests
      template:
        src: "{{ playbook_dir }}/templates/idp-mgmt-manifests.yaml"
        dest: /tmp/idp-mgmt-manifests.yaml
        mode: '0644'
    - name: Create catalogsource
      environment:
        KUBECONFIG: "{{ kubeconfig_file }}"
      shell: |
        {{ kubectl_cmd }} delete -f /tmp/idp-mgmt-manifests.yaml || true
        sleep 10
        {{ kubectl_cmd }} apply -f /tmp/idp-mgmt-manifests.yaml

  - name: Apply operator manifests
    shell: |
      if [ -d idp-mgmt-operator ]; then
        rm -rf idp-mgmt-operator
      fi
      git clone https://github.com/identitatem/idp-mgmt-operator.git
      cd idp-mgmt-operator
      make deploy
      cd ..
    register: output
    when: false

  - name: 'make deploy'
    debug:
      msg: 
      - "{{ output.stdout_lines }}"
    when: false

  - name: Generate authrealm
    shell: |
      export GITHUB_APP_CLIENT_ID={{ GITHUB_APP_CLIENT_ID }}
      export GITHUB_APP_CLIENT_SECRET={{ GITHUB_APP_CLIENT_SECRET }}
      export GITHUB_APP_CLIENT_ORG={{ GITHUB_APP_CLIENT_ORG }}
      export IDP_NAME=sample-idp
      export NAME=authrealm-sample
      export NS=authrealm-sample-ns
      cd idp-mgmt-operator/hack
      env | grep GITHUB
      ./generate-cr.sh
      cat /tmp/authrealm-sample.yaml
    register: output
    when: false

  - name: Authrealm manifest
    debug:
      msg: 
      - "{{ output.stdout_lines }}"
    when: false