---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: idp-mgmt-config-catalog
  namespace: openshift-marketplace
spec:
  displayName: identity configuration management for Kubernetes Catalog
  image: quay.io/identitatem/idp-mgmt-operator-catalog:{{ IDP_MGMT_VERSION }}
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: v1
kind: Namespace
metadata:
  name: idp-mgmt-config
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  # generateName: idp-mgmt-config-
  name: idp-mgmt-config
  namespace: idp-mgmt-config
spec:
  targetNamespaces:
  - idp-mgmt-config
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/idp-mgmt-operator.idp-mgmt-config: ""
  name: idp-mgmt-operator
  namespace: idp-mgmt-config
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: idp-mgmt-operator
  source: idp-mgmt-config-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: idp-mgmt-operator.v0.1.0
